### ISSUE TITLE
how to  predict structure from single sequence without msa? 

### ISSUE THREAD

**Issue by lyjdwh** [lucidrains/tr-rosetta-pytorch#2]
I know from [trdesign](https://github.com/gjoni/trDesign/blob/master/02-GD/notebooks/TrDesign_GD_demo.ipynb) that trrosetta can predict structure from single sequence.

I wonder how to do that using tr-rosetta-pytorch. Thanks very much!

**Comment by lucidrains** [comment]
@lyjdwh from what i heard, you can just feed the sequence in as the MSA and it should work!

**Comment by lyjdwh** [comment]
Yes, it works, thanks very much!
